### ISSUE TITLE
Possible COVID-19 Exposure notification should click through to more information

### ISSUE THREAD

**Issue by GeorgeGardiner** [nhsx/covid-19-app-ios-ag-public#11]
**Describe the bug**
The "Possible COVID-19 Exposure" notification does not click through to any useful information about why it was generated. 

**To Reproduce**
An exposure is generated which falls below the threshold for further action, but is notified to the user by the operating system.

**Expected behaviour**
If the notification cannot be suppressed, clicking should take the user to a view which explains that this exposure is below the threshold for further action.

**Screenshots**
![Image from iOS](https://user-images.githubusercontent.com/5549378/95109654-cd5c3c80-0734-11eb-92be-376c49bd36ce.png)

**Smartphone (please complete the following information):**
 - Device: iPhone10,6
 - OS: 14.0.1
 - Browser n/a
 - Version: Build 18A393

**Additional context**

**Comment by mrjonstrong** [comment]
Just seen this on a Pixel 2 running Android 11. Created issue on Android app https://github.com/nhsx/covid-19-app-android-ag-public/issues/25

**Comment by mrjonstrong** [comment]
I've just received the same on an iPhone 11
Also running iOS 14.0.1 Build 18A393
App version 3.6.1 (191)

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. We do welcome product suggestions on the above link - https://faq.covid19.nhs.uk/create-case/ and endeavour to respond to technical issues here. We are constantly looking at ways to improve the messaging & clarity of language within the app. Some improvements in this area have been deployed into version 3.7 of the app, now on the App Store, and others will follow.
