### ISSUE TITLE
App does not open past launch screen since 3.10 App Store update

### ISSUE THREAD

**Issue by galexite** [nhsx/covid-19-app-ios-ag-public#13]
**Describe the bug**
Since updating the app to 3.10 from the App Store, I can no longer open the app on my iPhone XR (model number MRY52B/A) running iOS 14.0.

The app hangs on the launch screen, as in the following screenshot:

![App displaying launch screen](https://user-images.githubusercontent.com/6300838/98687862-1de13e00-2362-11eb-8ae0-c7ccb49be772.png)

This occurs even after removing the app from the multitasking menu and attempting to re-open the app from the home screen, or from Settings app's 'View Exposures in App' hyperlink.

**To Reproduce**
1. Update app from App Store to version 3.10.
2. Go to Home Screen
3. Click on NHS COVID-19 app icon
4. Wait indefinitely for app to pass launch screen.

**Expected behavior**
The app opens and proceeds to the first view controller as normal.

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 14.0
 - App Version: 3.10

**Comment by galexite** [comment]
After upgrading to iOS 14.2, the app appears to work normally.

**Comment by TimothyChilvers** [comment]
Same issue - iPhone XR, iOS 14.1
Additionally, my installation has lost the app icon, reverting to the Xcode default app icon.

**Comment by 29antonioac** [comment]
The app stopped working in my wife's iPhone 11 with iOS 14.1. Updating to 14.2 solved the issue.

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. This issue affected a small number of iOS users. Upgrading to the latest version of the app should fix the problem in most cases. For more details please see the FAQ at https://faq.covid19.nhs.uk/article/KA-01349/en-us  @TimothyChilvers - thanks for the information about the app icon - I will pass this on to the developers.
