### ISSUE TITLE
iOS 12.5.1 support 

### ISSUE THREAD

**Issue by learntofly83** [nhsx/covid-19-app-ios-ag-public#15]
EDIT: as if by magic, Apple just released iOS 12.5.1 10 minutes ago!

—

Apple added the Covid Exposure Notifications framework as an unexpected update to legacy devices (iPhone 5S/iPhone 6 etc) in iOS 12.5 a few weeks back.

https://support.apple.com/en-us/HT209084#125

The current app on the App Store requires a minimum of iOS 13.5. Which was the previous minimum version with the framework support.

Could the app now be altered to work on iOS 12.5 on these legacy devices, increasing the availability to more people?

Thanks

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. We do welcome product suggestions at  https://faq.covid19.nhs.uk/create-case/ and endeavour to respond to technical issues here. We are constantly evaluating our device and OS version support, so thanks for the suggestion.

**Comment by ChristopherHackett** [comment]
@nhs-covid19 Scotland, Northern Ireland and even Jersey apps have been updated to support these older devices nearly 2 months ago yet England & Wales is still unsupported!

**Comment by learntofly83** [comment]
I haven’t followed the progress with the app since I posted this issue but I must say I was disappointed with the reply. 

I’ve just tried to download on the now recently released 12.5.2 - which has the exposure notifications API and the AppStore store me that the app requires iOS 13.5. I would wager just changing the minimum supported version in Xcode would produce an app that works on iOS 12.5.x

Why have a GitHub issue tracker to just post generic customer service type replies to the issues?

**Comment by nhs-covid19** [comment]
Thanks for your comments - we monitor GitHub issues to see when people report software defects, which we then feed into our development process. Features and enhancements are better requested through the product suggestion flow, using the link above. Unfortunately, just changing the target version in Xcode isn't sufficient to build this for iOS12.5.x. The supported device and OS list is always up-to-date at: https://faq.covid19.nhs.uk/article/KA-01167/en-us

**Comment by learntofly83** [comment]
Hi,

I’m not sure whether the original point was missed or whether I’m flogging a dead horse but apple backported the Exposure Notifications framework for legacy devices into iOS 12.5 quite unexpectedly a few months back, this means that the iPhone 5S for instance now has and OS capable of handling the Exposure Notifications framework and supports BLE.

It would obviously be beneficial to take up if legacy devices which apple have unexpectedly backported the frameworks needed to support your app onto, were enabled to use your app.

My comment about the target version in Xcode wasn’t flippant,. I understand this wouldn’t work PRE iOS 12.5 But now the framework has been backported into 12.5.x has anyone actually tried to enable it?

I’ll try the app on an iPhone 5S on 12.5.2 via TestFlight if you so wish?

**Comment by ChristopherHackett** [comment]
@nhs-covid19 The linked support page is incorrect.
https://faq.covid19.nhs.uk/article/KA-01167/en-us

> This is because the app has been designed to use technologies that are only available in these versions 

The devices in question have both the required hardware (BLE) and operating systems that supports the underlying feature (Exposure Notification Framework). This is proven by the fact these devices can download one of the other apps (Scotland, Northern Ireland & Jersey) and tracing will work inbound (people you come into contact with and later test positive will flag you up for self isolation) but not outbound (as far as I know you can not register England and Wales test result into the other apps).

It is completely understandable for support not to have been "flicked on" at release of iOS 12.5 but its embarrassing that the app to protect the most populous nation for the NHS is alone in not supporting these devices. Not even a hint that it's planned to be updated for these devices.
