### ISSUE TITLE
Prompts user if they're under 16 or over 16; should be 16 or under

### ISSUE THREAD

**Issue by KevinMonk** [nhsx/covid-19-app-ios-ag-public#3]
It asks the user if they're over 16 or under 16. If they're 16, they're neither.

Suggest changing it to "16 or under"

**Comment by zaphodikus** [comment]
Thank you for raising this for me Kevin, hope getting minor things correct early, will drive up adoption and simplification.

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. We do welcome product suggestions on the above link - https://faq.covid19.nhs.uk/create-case/ and endeavour to respond to technical issues here. We are constantly looking at ways to improve the clarity of language within the app.
