### ISSUE TITLE
Risk location 

### ISSUE THREAD

**Issue by mattbough1** [nhsx/covid-19-app-ios-ag-public#4]
Risk level should be dynamic using current location to gain knowledge of risk in local area that the user is in.

Suggest also being able to change postcode, as users could move / have a second residence.

**Comment by DMBryant** [comment]
This would require the app to have access to your GPS location which I don't think is allowed whilst also having access to the API. Wasn't that the whole issue with the original app?

**Comment by mattbough1** [comment]
Can it not be optional? Or as a work around have a manual entry option for the postcode so the users can check the local risk?

**Comment by DMBryant** [comment]
Manual entry of local postcode to check would be a good alternative!

**Comment by mattbough1** [comment]
Also, some explanation of the postcode is good. A couple of people I know seem to think that it is always tracking just in that location of the postcode and is not actually scanning in the local area against other users. (I know this is explained but it would be good to be more obvious to users who do not pay much attention haha!

**Comment by paulchambers** [comment]
You can change the postcode manually under "about this app/manage my data"

As DMBryant mentioned they are prevented by Apple/Google policy from using location APIs in an app with access to the exposure notification APIs

**Comment by mattbough1** [comment]
But why not make it more obvious how to change.
Better still a map colour coded with the risk areas.

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. The app does not make use of the GPS location of the device, and to do so would be contrary to the EN API License Agreement from Apple - Google has a similar clause - This agreement is documented at https://developer.apple.com/contact/request/download/Exposure_Notification_Addendum.pdf
We are always looking to make the application easier to use and understand, and will look into your suggestions about changing postal districts - so thank you for the suggestion. Product suggestions and feedback are welcomed at https://faq.covid19.nhs.uk/create-case/
