### ISSUE TITLE
checkins can be faked - a distinctive, unique sound would help to confirm the app is actually being used.

### ISSUE THREAD

**Issue by smagdali** [nhsx/covid-19-app-ios-ag-public#9]
**Describe the bug**

(on the border between a bug and a feature request, I know)

Twice today (1-10-20), in Pret, I saw someone hold up their phone as if they were scanning the barcode, when in fact they were just pretending. This undermines the effectiveness of the test and trace system, and could do so substantially if it becomes a widely used behavioural anti-pattern. 

A distinctive audio confirmation ("Thanks for checking in with NHS Test and Trace!")  of a successfully checkin would be a useful indicator to venue employees and people nearby, and hence act as a strong social cue to do the right thing.

**To Reproduce**

Check in at a venue.

**Expected behavior**

Successful checkins play a distinctive 'bong' or spoken acknowledgement.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS:  IOS 14.2beta

**Comment by michaelpapworth** [comment]
From the description you’ve provided here I believe this to be a feature request, as there is no defect in the application. Essentially the problem you’re trying to solve is the one of consumer honesty, whilst it’s not law in the UK to scan the QR codes to check in, I wouldn’t consider it a problem. Audible feedback won’t be guaranteed as the device volume settings will override this.  It’s also not an accessible solution for the hard of hearing.

**Comment by nhs-covid19** [comment]
Thanks for your interest in the NHS Covid-19 project. You raise an interesting point, however the current functionality with regard to audio acknowledgements (there are none) is as intended and not a software defect. We do welcome feedback on the features and functionality of the app at https://faq.covid19.nhs.uk/create-case/
